name: PlayersIndex
version: ${project.version}
main: com.github.nishitox.playersindex.PlayersIndex
api-version: 1.15

commands:
  playersindex:
    usage: "§cusage: /playersindex set [player] [groupByTeam]"
    permission: op